version: '3.8'

services:
  bot-app:
    build: .
    container_name: bot-app
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - TELEGRAM_BOT_TOKEN=your_bot_token_here
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./media:/app/media
      - ./logs:/app/logs
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900" # VNC для отладки (если нужно)
    shm_size: '2gb'
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - default